version: '3.8'

services:
  socks5-proxy:
    build: .
    container_name: alpine-socks5-proxy
    ports:
      - "1080:1080"
    volumes:
      - proxy
    restart: unless-stopped
volumes:
  proxy: {}
