services:
  alpine:
    build:
      context: .
      dockerfile: alpine.Dockerfile
      args:
        AIP: ${AIP}
        AUSER: ${AUSER}
        APASSWORD: ${APASSWORD}
    restart: always
    ports: 
      - "1080:1080"
    tty: true
    volumes:
      - alpine:/alpine

volumes:
  alpine: {}
