services:
  alpine:
    build:
      context: .
      dockerfile: alpine.Dockerfile
    restart: always
    ports: 
      - 80
    tty: true
    volumes:
      - alpinee:/alpine

  volumes:
    alpinee: {}
