services:
  alpine:
    build:
      context: .
      dockerfile: alpine.Dockerfile
    restart: always
    ports: 
      - "1080:1080"
    tty: true
    volumes:
      - alpine:/alpine

volumes:
  alpine: {}
